### ISSUE TITLE
Stub patch links is stubbing put

### ISSUE THREAD

**Issue by christophwong** [alphagov/gds-api-adapters#458]
The V2 publishing-api helper ["#patch_links"](https://github.com/alphagov/gds-api-adapters/blob/master/lib/gds_api/publishing_api_v2.rb#L73) uses http PATCH method, but in the test helpers ["#stub_publishing_api_patch_links"](https://github.com/alphagov/gds-api-adapters/blob/master/lib/gds_api/test_helpers/publishing_api_v2.rb#L30) uses PUT.
This mismatch makes the stub method fail to stub out any calls to patch_link.

**Comment by tijmenb** [comment]
Fixed by https://github.com/alphagov/gds-api-adapters/pull/461.

**Comment by elliotcm** [comment]
Released as version 29.1.1
