### ISSUE TITLE
Links to docs, test helper docs appear to be broken

### ISSUE THREAD

**Issue by 36degrees** [alphagov/gds-api-adapters#532]
The [links in the readme](https://github.com/alphagov/gds-api-adapters/blob/master/README.md#gds-api-adapters) to the docs and test helper docs on rubydoc.info appear to be broken. Have they been moved elsewhere?

![screenshot 2016-07-06 09 23 30](https://cloud.githubusercontent.com/assets/121939/16611778/5bc6ccb2-435b-11e6-84f8-81fc53c0ecf7.png)

**Comment by tijmenb** [comment]
That's odd. They seem to have vanished. 

I've added the project again (http://www.rubydoc.info/github - click "Add project"). It seems to have appeared again.

**Comment by 36degrees** [comment]
Thanks! I would have done that, but wanted to check they hadn't been removed intentionally.

**Comment by edent** [comment]
Seem to have disappeared again.
