### ISSUE TITLE
GDS API Adapters no longer work with 'gov.uk/api/organisations'.

### ISSUE THREAD

**Issue by benthorner** [alphagov/gds-api-adapters#839]
This started when trying to run tests in the `transition-config` repo, which make the following call `GdsApi::Organisations.new('http://gov.uk').organisations`. This only return 20 entries.

Further investigation shows that the adapter code is unrolling a paginated response from `gov.uk/api/organisation`, using a header which no longer exists.

I started changing the API adapters to work with the response body instead of the missing headers, but it might be better to figure out why the headers are no longer available and fix that. Here's an example query with the right headers.

```
curl --verbose -H 'Host: whitehall-admin' localhost/api/organisations`

......

< X-Content-Type-Options: nosniff
< Link: <http://whitehall-admin/api/organisations?page=2>; rel="next", <http://whitehall-admin/api/organisations?page=1>; rel="self"
< Cache-Control: max-age=900, public
```

**Comment by rubenarakelyan** [comment]
Will be fixed by https://github.com/alphagov/collections/pull/770
